[package]
name = "vdash"
description = "SAFE Network Node Dashboard"
version = "0.6.1"
authors = ["Mark <git@happybeing.com>"]
license = "GPL-3.0"
homepage = "https://github.com/happybeing/vdash"
repository = "https://github.com/happybeing/vdash"
readme = "README.md"
exclude = [".github"]
keywords = ["utility", "logfile", "monitor", "cli", "safenetwork"]
categories = ["command-line-utilities"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["termion", "crossterm"]

[dependencies]
tokio = { version = "0.2.22", features = ["sync", "macros"] }
tokio-macros = "0.3.1"
termion = { version = "1.5", optional = true }
crossterm = { version = "0.17", optional = true }
linemux = "0.1.3"
structopt = "~0.3.15"
futures = "0.3.5"
regex = "1.3.9"
tempfile = "3.1.0"
time = "0.2.16"
lazy_static = "1.4.0"
chrono = "0.4.15"
bincode = "1.3.1"
byte-unit = "4.0.9"
fs2 = "0.4.3"
rand = "0.7.3"
log = "0.4.11"
env_logger = "0.7.1"
#unicode-segmentation = "1.2"
#unicode-width = "0.1"

[target.'cfg(not(windows))'.dependencies]
tui = { version = "0.11.0", features = ["termion", "crossterm"], default-features = false }

[target.'cfg(windows)'.dependencies]
tui = { version = "0.11.0", features = ["crossterm"], default-features = false }

[[bin]]
name = "vdash"
required-features = ["termion"]
path = "src/bin/vdash-termion.rs"

[[bin]]
name = "vdash-crossterm"
required-features = ["crossterm"]
path = "src/bin/vdash-crossterm.rs"
